# Generated by Django 5.2 on 2025-04-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('png_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='viewed_articles',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dislike'), (2, 'Neutral'), (3, 'Like')]),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_categories',
            field=models.CharField(help_text='Comma-separated list of preferred categories.', max_length=200),
        ),
    ]
